### ISSUE TITLE
hubble 1.5.0 release版本导入数据出错

### ISSUE THREAD

**Issue by gtcslance** [hugegraph/hugegraph-hubble#281]
Log里的报错信息为

2020-12-15 12:28:27.417 ERROR 90737 --- [lTaskExecutor-6] com.baidu.hugegraph.loader.util.Printer  : Failed to load, cause: Cannot deserialize value of type `com.baidu.hugegraph.type.define.GraphMode` from String "LOADING": not one of the values accepted for Enum class: [NONE, RESTORING, MERGING]
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]

com.baidu.hugegraph.exception.ServerException: Cannot deserialize value of type `com.baidu.hugegraph.type.define.GraphMode` from String "LOADING": not one of the values accepted for Enum class: [NONE, RESTORING, MERGING]
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]
    at com.baidu.hugegraph.exception.ServerException.fromResponse(ServerException.java:47) ~[hugegraph-client-1.9.1.jar:1.5.0]
    at com.baidu.hugegraph.client.RestClient.checkStatus(RestClient.java:93) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
    at com.baidu.hugegraph.rest.AbstractRestClient.put(AbstractRestClient.java:231) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
    at com.baidu.hugegraph.rest.AbstractRestClient.put(AbstractRestClient.java:217) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
    at com.baidu.hugegraph.rest.AbstractRestClient.put(AbstractRestClient.java:205) ~[hugegraph-common-1.8.1.jar:1.8.1.0]
    at com.baidu.hugegraph.api.graphs.GraphsAPI.mode(GraphsAPI.java:60) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
    at com.baidu.hugegraph.driver.GraphsManager.mode(GraphsManager.java:46) ~[hugegraph-client-1.9.1.jar:1.9.1.0]
    at com.baidu.hugegraph.loader.executor.LoadContext.setLoadingMode(LoadContext.java:139) ~[hugegraph-loader-0.11.1.jar:na]
    at com.baidu.hugegraph.loader.HugeGraphLoader.load(HugeGraphLoader.java:107) ~[hugegraph-loader-0.11.1.jar:na]
    at com.baidu.hugegraph.entity.load.LoadTask.run(LoadTask.java:169) [hubble-be-1.5.0.jar:1.5.0]
    at com.baidu.hugegraph.handler.LoadTaskExecutor.execute(LoadTaskExecutor.java:36) [hubble-be-1.5.0.jar:1.5.0]
    at com.baidu.hugegraph.handler.LoadTaskExecutor$$FastClassBySpringCGLIB$$b9aa284d.invoke(<generated>) [hubble-be-1.5.0.jar:1.5.0]
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) [spring-core-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.1.9.RELEASE.jar:5.1.9.RELEASE]

**Comment by gtcslance** [comment]
发现是hugegraph server版本不对，用最新版release的就可以了
