### ISSUE TITLE
hubble元数据配置删除bug

### ISSUE THREAD

**Issue by pdong524** [hugegraph/hugegraph-hubble#315]
hubble元数据配置中，想要删除某一类型的边，点击删除之后显示删除成功，但事实上该类型的边并未删除
在java代码中删除该类型的边时，出现“ClientException”错误
具体代码如下：
schema.removeEdgeLabel("buy");
错误报告如下：
Exception in thread "main" com.baidu.hugegraph.rest.ClientException: Task '26' is failed, result is 'null'
	at com.baidu.hugegraph.api.task.TaskAPI.waitUntilTaskSuccess(TaskAPI.java:116)
	at com.baidu.hugegraph.driver.SchemaManager.removeEdgeLabel(SchemaManager.java:162)
	at com.baidu.hugegraph.driver.SchemaManager.removeEdgeLabel(SchemaManager.java:157)
	at cn.nlp.kg.visualization.Test.main(Test.java:51)

**Comment by imbajin** [comment]
Hubble 相关的问题, 请给一下截图或者具体一点的**复现步骤**, 方便测试同学复现确认 (最好能提供一个最小的复现数据集)

另外相关的版本也麻烦提供一下, Hubble 和 Client 的报错和复现可以分隔开写一下 ~


PS: issue 的格式和排版帮调整了一下, 后续也可以按类似格式更新错误信息

**Comment by pdong524** [comment]
我刚删除成功了，具体操作是先清了一下库，使用命令是官网提供的命令：curl -X DELETE http://localhost:8080/graphs/hugegraph/clear?confirm_message=I%27m+sure+to+delete+all+data，
然后去hubble里面删除元数据配置就成功了。
理论上来说不清库也可以直接删除元数据配置，我猜出现上述问题的原因可能是我的数据量太多了，没有清库直接删除元数据的话服务器需要运行一段时间才可以完成，而hubble在点击了“删除”按钮之后直接显示“删除成功”但实际上并没有删完，给了一种删除失败的假象。建议前端同学可以调整一下，在全部删除完成之后再显示“删除成功”

**Comment by imbajin** [comment]
感谢反馈和建议, 默认情况印象里我记得删除元数据, 它会默认生成一个异步的任务去删除, 然后返回一个 taskID, 可能这里没有取获取异步任务的具体结果和执行百分比, 直接返回的成功是提交删除任务成功.

以后应需要改进
